### ISSUE TITLE
Can't set default value for a bool

### ISSUE THREAD

**Issue by JaredRohe** [jessevdk/go-flags#175] opened 2016-06-06 23:48 UTC
``` 
type MyConfig struct {
    MyBool      bool   `long:"my_bool" `

}

parser = flags.NewParser(&CatalogConfig, flags.Default)

_, err: = parser.Parse()

// err == nil is true here!!! =)
```
```

type MyConfig struct {

    MyBool      bool   `long:"my_bool" default:"true"`   

   // Notice the only difference here from above  is default:"true"

}


_, err: = parser.Parse()

// err == nil is false here  =( =( 

```

**Comment by jessevdk** [comment] 2016-06-07 16:54
Duplicate of https://github.com/jessevdk/go-flags/issues/80.

**Closed by jessevdk** 2016-06-07 16:54 UTC
