### ISSUE TITLE
Newlines for descriptions (for documenting choices)

### ISSUE THREAD

**Issue by mblaschke** [jessevdk/go-flags#225] opened 2017-04-05 11:01 UTC
is there a possiblity to add newlines for descriptions? or a possiblity to document choices?

**Comment by jkieboom** [comment] 2017-04-14 08:56
Duplicate of #124 and #92, still same answer.

**Comment by jessevdk** [comment] 2017-04-14 08:56
Duplicate of #124 and #92.

**Closed by jessevdk** 2017-04-14 08:56 UTC
