### ISSUE TITLE
Options work partially without '=' and partially returns an error

### ISSUE THREAD

**Issue by KaiHofstetter** [jessevdk/go-flags#239] opened 2017-08-07 12:29 UTC
1) If you don't use 'positional-args' options without '=' returns an error:
```
$ cli cmd --option value
Command ... does not support extra arguments: value
```
2) If you use `positional-args:"true"` the option value is interpreted as positional argument which brings two problems:
```
$ cli cmd --option value positional-arg
Command ... does not support extra arguments: positional-arg
# So, 'value' was interpreted as positional arg and it complains about the real positional arg.

$ cli cmd --option value
# It runs, but assumes value as positional argument. Which is probably the most dangerous problem here.
```
3) If you use `positional-args:"true" required:"true"` you can use options without '=':
```
$ cli cmd --option value positional-arg
# cmd runs...
```

**Comment by jessevdk** [comment] 2017-08-07 19:17
This is all by design, the documentation on `optional` says:

> optional:       if non-empty, makes the argument of the option optional. When an
                argument is optional it can only be specified using
                --option=argument

**Comment by KaiHofstetter** [comment] 2017-08-10 08:41
Yes, however if the cmd has a required positional arg, than the argument can be specified as `--option arg`.

For example: `cli cmd --option value REQUIRED` works.

**Comment by jessevdk** [comment] 2018-09-24 07:01
I don't think that works as you would think. It will parse yes, but `value` will be your required positional arg, and `REQUIRED` will be part of the remaining args. I appreciate that this is confusing, but I still don't want to change the behavior of optional arguments. The situation is simply ambiguous and we'll have to choose to parse it in some consistent way. It may be better to just not use optional arguments in this situation.

**Closed by jessevdk** 2018-09-24 07:01 UTC
