### ISSUE TITLE
more complex default values that may result in errors

### ISSUE THREAD

**Issue by cppforlife** [jessevdk/go-flags#155] opened 2015-12-19 21:29 UTC
I've got a few types that I'm using for options (e.g. DirOrCWDArg) that need to be filled with default values. Now of course golang has zero values which work great in a lot of cases; however, it's a bit annoying to use them for more complex cases that may result in errors (e.g. os.Getwd()).

For example, I'd like to fill out DirOrCWDArg with a current working dir before I have to use this inside command body:

```
type DirOrCWDArg string

func (a *DirOrCWDArg) UnmarshalFlag(data string) error {
	if len(data) == 0 || data == "." {
		path, err := os.Getwd()
		if err != nil {
			return err
		}

		*a = DirOrCWDArg(path)
	} else {
		*a = DirOrCWDArg(data)
	}

	return nil
}
```

I could move os.Getwd logic down into the command body but then I would have to duplicate that code which is not ideal. My current work around for DirOrCWDArg is to include `default:"."` (a sentinel value) so that in UnmarshalFlag (that now will be called) I could compare with sentinel value and fill the option with a proper default.

Doing a quick search in the code, I noticed that maps are populated with an empty map instead of keeping them as nil. So it seems there is already special casing for default values. I am thinking of adding an additional interface to cover filling default values. Wdyt?

/cc @vito Got any examples in fly cli?

**Comment by jessevdk** [comment] 2016-02-07 07:51
The default values are really supposed to be in the "syntax" of the command line argument, since they are just simple strings. Note that you don't _have_ to use the `default` tag. You can just initialize your struct.

I would probably be ok with an additional `InitializeFlag` or so method that you can implement and that will be called before the parsing of flags.

**Comment by jessevdk** [comment] 2016-02-27 08:23
Would that work?

**Comment by jessevdk** [comment] 2016-05-21 09:50
No new information has been provided, I'm closing this issue. Please feel free to reopen it if the problem is still valid.

**Closed by jessevdk** 2016-05-21 09:50 UTC
Labels: needinfo

**Comment by cppforlife** [comment] 2016-08-23 07:55
@jessevdk finally circled around to this issue...

> You can just initialize your struct.

Unfortunately that doesnt work for slices and it becomes way too easy to forget to initialize as more options are added.

I'm assuming you are proposing `InitializeFlag` on the flag type itself, similarly to how `UnmarshalFlag` is called? I think that would work though for some of our flags we would like to configure it with other dependencies (want to avoid singletons). Currently we have something like this:

```
goflags.FactoryFunc = func(val interface{}) {
	stype := reflect.Indirect(reflect.ValueOf(val))
	if stype.Kind() == reflect.Struct {
		field := stype.FieldByName("FS")
		if field.IsValid() {
			field.Set(reflect.ValueOf(myFS))
		}
	}
}
```

and `FactoryFunc` is called right before `UnmarshalFlag`. Of course I would love to kill this off. May be you have some ideas of how to consolidate injection/default-ing behaviour?

**Comment by jessevdk** [comment] 2016-08-25 12:51
I really think this is making things more complicated then they have to be. Just initialize your values at the beginning of the program? I don't see how that is more error prone, or more complicated than adding additional abstractions that would initialize such values as part of the flags parsing.

**Comment by cppforlife** [comment] 2016-08-25 21:44
> Just initialize your values at the beginning of the program?

I want to avoid global variables and because I have a few slice types I cannot initialize flag structs before calling ParseArgs.
