### ISSUE TITLE
Inconsistent quoting for unknown flag error

### ISSUE THREAD

**Issue by benpbrown** [jessevdk/go-flags#207] opened 2016-12-05 19:49 UTC
https://github.com/jessevdk/go-flags/blob/master/parser.go#L604

On that line, the opening quote is a backtick and the closing quote is a single quote. My expectation was that the opening/closing quote would be the same.

**Comment by jessevdk** [comment] 2016-12-15 10:53
Duplicate of https://github.com/jessevdk/go-flags/issues/167.

**Closed by jessevdk** 2016-12-15 10:53 UTC
