### ISSUE TITLE
Add support for nicksnyder/go-i18n

### ISSUE THREAD

**Issue by krishicks** [jessevdk/go-flags#162] opened 2016-02-11 19:46 UTC
Hi,

I've seen some projects using go-flags successfully and would love to transition the [Cloud Foundry cli](https://github.com/cloudfoundry/cli) to using it, but I've run into a blocker: i18n support.

Currently we get i18n support via [nicksnyder/go-i18n](https://github.com/nicksnyder/go-i18n). Given the description of flags in go-flags is embedded in a struct tag, it's seemingly not compatible with go-i18n.

I was wondering if there's any desire to add support for it, or if there's an existing workaround that can be done.

**Comment by jessevdk** [comment] 2016-02-11 21:50
Not sure about native support, command line tools are often not translated, especially not the command line arguments. However, I see how it could be useful. I'm not sure exactly how go-i18n works, but what you could probably try is something like this (pseudo):

```go
func newParser() *flags.Parser {
  p := flags.NewParser(&data, flags.Default)
  translate(p)

  return p
}

func translate(g *flags.Group) {
  for option := range g.Options() {
    option.Description = T(option.Description)
  }

  for group := range g.Groups() {
    translate(group)
  }
}
```

**Comment by jessevdk** [comment] 2016-05-21 09:49
No new information has been provided, I'm closing this issue. Please feel free to reopen it if the problem is still valid.

**Closed by jessevdk** 2016-05-21 09:49 UTC
Labels: needinfo

**Comment by krishicks** [comment] 2016-05-22 23:52
We ended up using the suggestion, implemented as such: https://github.com/cloudfoundry/cli/blob/master/cf/i18n/i18n.go#L61

It's been working well so far.
